#!/usr/bin/env python3
"""Write assets/expected_topology.csv: the ICE2 backend fabric as designed.

This file is the reference for the "Cabling vs UFM" check: every link UFM sees is
compared with it (NetBox is reported alongside, not used as the truth). Edit the
rules below, or edit the CSV directly for one-off exceptions, and re-run:

    python3 scripts/build_expected_topology.py

Rules (ICE2 backend, 36 spines x 64 leaves, 16 scalable units):
  L1  Leaf-spine full mesh, two cables per pair:
      leaf j port sw(36+i)pM  <->  spine i port sw(j)pM      (i=1..36, j=1..64, M=1,2)
  G1  4 pods of 16 leaves; within a pod, rail r = leaves 4(r-1)+1..4r; scalable unit k
      takes the k-th leaf of every rail:  SU = 4*(pod-1)+k.
  G2  Leaf downlink swNpM (N=1..36) is tray slot 2(N-1)+M of that leaf's SU; every tray
      uses the same slot (port) on all four leaves of its SU.
  G3  Rail r reaches the tray's adapter mlx5_(r-1) (RDMA r).
"""
import csv
from pathlib import Path

HOST = "sys1-ice2-p-swi-"
OUT = Path(__file__).resolve().parent.parent / "assets" / "expected_topology.csv"


def su_of_leaf(leaf: int):
    pod, offset = divmod(leaf - 1, 16)
    rail, k = divmod(offset, 4)
    return pod * 4 + k + 1, pod + 1, rail + 1


def rows():
    for j in range(1, 65):
        for i in range(1, 37):
            for m in (1, 2):
                yield ["leaf-spine", HOST + "bel%d" % j, "sw%dp%d" % (36 + i, m), HOST + "bes%d" % i, "sw%dp%d" % (j, m), "L1"]
    for j in range(1, 65):
        su, pod, rail = su_of_leaf(j)
        for n in range(1, 37):
            for m in (1, 2):
                slot = 2 * (n - 1) + m
                yield ["leaf-gpu", HOST + "bel%d" % j, "sw%dp%d" % (n, m), "SU%d slot %d" % (su, slot), "mlx5_%d" % (rail - 1), "G1-G3"]


def main() -> int:
    with OUT.open("w", newline="", encoding="utf-8") as handle:
        handle.write("# ICE2 backend fabric as designed (generated by scripts/build_expected_topology.py; rules in that file).\n")
        handle.write("# leaf-gpu rows name the tray slot, not the tray: any tray may sit in a slot, but all four rails must.\n")
        w = csv.writer(handle, lineterminator="\n")
        w.writerow(["link_type", "a_device", "a_port", "b_device", "b_port", "rule"])
        n = 0
        for row in rows():
            w.writerow(row)
            n += 1
    print("Wrote %s (%d expected links)" % (OUT, n))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
