#!/usr/bin/env python3
"""Write assets/expected_topology.csv: the LON14 InfiniBand backend fabric as designed.

The inferred rules: used by the cabling check where the approved design file has no entry
(or when there is no design file). Derived from the LON14 NetBox cabling, which follows
them on every one of its 4,608 leaf-spine and 4,608 leaf-GPU cables. Re-run after editing:

    python3 scripts/build_expected_topology.py

Rules (LON14 sys1 InfiniBand backend, 36 Q3400 spines x 64 Q3400 leaves, 16 scalable units):
  L1  Leaf-spine full mesh, two cables per pair, lanes crossed:
      leaf j port sw(73-i)p(3-M)  <->  spine i port sw(j)pM      (i=1..36, j=1..64, M=1,2)
  G1  A scalable unit is four consecutive leaves, one per rail:
      SU k = leaves 4(k-1)+1 .. 4k; rail r = leaf 4(k-1)+r.  4 pods of 4 SUs (16 leaves).
  G2  Leaf downlink swNpM (N=1..36) is tray slot 2(N-1)+M of that leaf's SU; every host
      uses the same slot (port) on all four leaves of its SU (gpuN: SU ceil(N/72), slot (N-1)%72+1).
  G3  Rail r reaches the host's adapter mlx5_(r-1) (RDMA r).
"""
import csv
from pathlib import Path

HOST = "sys1-lon14-p-swi-"
OUT = Path(__file__).resolve().parent.parent / "assets" / "expected_topology.csv"


def su_of_leaf(leaf: int):
    """(su 1..16, pod 1..4, rail 1..4) for leaf 1..64."""
    su, rail = divmod(leaf - 1, 4)
    return su + 1, su // 4 + 1, rail + 1


def rows():
    for j in range(1, 65):
        for i in range(1, 37):
            for m in (1, 2):
                yield ["leaf-spine", HOST + "bel%d" % j, "sw%dp%d" % (73 - i, 3 - m), HOST + "bes%d" % i, "sw%dp%d" % (j, m), "L1"]
    for j in range(1, 65):
        su, pod, rail = su_of_leaf(j)
        for n in range(1, 37):
            for m in (1, 2):
                slot = 2 * (n - 1) + m
                yield ["leaf-gpu", HOST + "bel%d" % j, "sw%dp%d" % (n, m), "SU%d slot %d" % (su, slot), "mlx5_%d" % (rail - 1), "G1-G3"]


def main() -> int:
    with OUT.open("w", newline="", encoding="utf-8") as handle:
        handle.write("# LON14 InfiniBand backend fabric as designed (generated by scripts/build_expected_topology.py; rules in that file).\n")
        handle.write("# leaf-gpu rows name the tray slot, not the host: any host may sit in a slot, but all four rails must.\n")
        w = csv.writer(handle, lineterminator="\n")
        w.writerow(["link_type", "a_device", "a_port", "b_device", "b_port", "rule"])
        n = 0
        for row in rows():
            w.writerow(row)
            n += 1
    print("Wrote %s (%d expected links)" % (OUT, n))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
